# Site settings
title: "Rhys Taus"
email: rhys.taus@NOSPAM.cern.ch
author: "Rhys Taus"
description: >- # this means to ignore newlines until "baseurl:"
  I am a PhD student at the University of Rochester working at the CMS experiment at CERN.
# URL settings (GitHub Pages)
baseurl: ""  # Leave blank for GitHub Pages
url: "https://rhysics.github.io"

# Theme settings
theme: minima

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
