
# Site settings
title: "Rhys Taus"
email: rhys.taus@NOSPAM.cern.ch
author: "Rhys Taus"
description: >- # this means to ignore newlines until "baseurl:"
  I am a PhD student at the University of Rochester working at the CMS experiment at CERN.
# URL settings (GitHub Pages)
baseurl: ""  # Leave blank for GitHub Pages
url: "https://rhysics.github.io"

github_username:  rhysics

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown

minima:
  navigation:
    - text: "Home"
      url: "/"
    - text: "About Me"
      url: "/about/"
    - text: "Research"
      url: "/research/"
