# Site settings
title: "My Academic Portfolio"
email: rhys.taus@NOSPAM.cern.ch
author: "Rhys Taus"
description: "An academic portfolio showcasing my research, teaching, and achievements."

# URL settings (GitHub Pages)
baseurl: ""  # Leave blank for GitHub Pages
url: "https://rhysics.github.io"

# Theme settings
theme: minima

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
