# Site settings
title: "Rhys Taus"
email: rhys.taus@NOSPAM.cern.ch
author: "Rhys Taus"
description: "My Personal website"

# URL settings (GitHub Pages)
baseurl: ""  # Leave blank for GitHub Pages
url: "https://rhysics.github.io"

# Theme settings
theme: minima

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
